version: 0.2

phases:
    install:
        commands:
            - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
            - dpkg -i hugo_0.52_Linux-64bit.deb
    build:
        commands:
            - hugo
            - echo "S3 Upload Beginning"
            - aws s3 sync public/ s3://atigerband.com/ --region us-east-1 --delete --acl public-read
            - echo "S3 Upload Complete"

    post_build:
        commands:
            - echo "Build complete"
